<?php

namespace ContainerLBrWqbv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NyNxjhiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nyNxjhi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nyNxjhi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'seguidorRepository' => ['privates', 'App\\Repository\\SeguidorRepository', 'getSeguidorRepositoryService', true],
            'utilidades' => ['privates', 'App\\Utilidades\\Utilidades', 'getUtilidadesService', true],
        ], [
            'seguidorRepository' => 'App\\Repository\\SeguidorRepository',
            'utilidades' => 'App\\Utilidades\\Utilidades',
        ]);
    }
}
