<?php

namespace Container9qgpuME;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4sFfOCpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4sFfOCp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4sFfOCp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comentarioRepository' => ['privates', 'App\\Repository\\ComentarioRepository', 'getComentarioRepositoryService', true],
            'converters' => ['privates', 'App\\Controller\\DTO\\DTOConverters', 'getDTOConvertersService', true],
            'utilidades' => ['privates', 'App\\Utilidades\\Utilidades', 'getUtilidadesService', true],
        ], [
            'comentarioRepository' => 'App\\Repository\\ComentarioRepository',
            'converters' => 'App\\Controller\\DTO\\DTOConverters',
            'utilidades' => 'App\\Utilidades\\Utilidades',
        ]);
    }
}
