<?php

namespace Container9qgpuME;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUtilidadesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Utilidades\Utilidades' shared autowired service.
     *
     * @return \App\Utilidades\Utilidades
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Utilidades/Utilidades.php';

        return $container->privates['App\\Utilidades\\Utilidades'] = new \App\Utilidades\Utilidades(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
