<?php

namespace ContainerMpYYvbC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_63NL9lIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.63NL9lI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.63NL9lI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'accessTokenRepository' => ['privates', 'App\\Repository\\AccessTokenRepository', 'getAccessTokenRepositoryService', true],
            'rolEntityRepository' => ['privates', 'App\\Repository\\RolEntityRepository', 'getRolEntityRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
            'utilidades' => ['privates', 'App\\Utilidades\\Utilidades', 'getUtilidadesService', true],
        ], [
            'accessTokenRepository' => 'App\\Repository\\AccessTokenRepository',
            'rolEntityRepository' => 'App\\Repository\\RolEntityRepository',
            'userRepository' => 'App\\Repository\\UsuarioRepository',
            'utilidades' => 'App\\Utilidades\\Utilidades',
        ]);
    }
}
