<?php

namespace ContainerMpYYvbC;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TxLU3I6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.txLU3I6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.txLU3I6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comentarioRepository' => ['privates', 'App\\Repository\\ComentarioRepository', 'getComentarioRepositoryService', true],
            'likerepository' => ['privates', 'App\\Repository\\LikeRepository', 'getLikeRepositoryService', true],
            'perfilRepository' => ['privates', 'App\\Repository\\PerfilRepository', 'getPerfilRepositoryService', true],
            'utils' => ['privates', 'App\\Utilidades\\Utilidades', 'getUtilidadesService', true],
        ], [
            'comentarioRepository' => 'App\\Repository\\ComentarioRepository',
            'likerepository' => 'App\\Repository\\LikeRepository',
            'perfilRepository' => 'App\\Repository\\PerfilRepository',
            'utils' => 'App\\Utilidades\\Utilidades',
        ]);
    }
}
