<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Perfil extends \App\Entity\Perfil implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'tipo_cuenta', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'foto_perfil', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'id_usuario', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'seguidor_principal', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'seguidor_follower', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'publicacion', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'id_perfil', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'comentario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'tipo_cuenta', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'foto_perfil', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'id_usuario', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'seguidor_principal', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'seguidor_follower', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'publicacion', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'id_perfil', '' . "\0" . 'App\\Entity\\Perfil' . "\0" . 'comentario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Perfil $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(?int $id): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion(?string $descripcion): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(?string $username): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoCuenta(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoCuenta', []);

        return parent::getTipoCuenta();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoCuenta(?string $tipo_cuenta): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoCuenta', [$tipo_cuenta]);

        parent::setTipoCuenta($tipo_cuenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFotoPerfil(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFotoPerfil', []);

        return parent::getFotoPerfil();
    }

    /**
     * {@inheritDoc}
     */
    public function setFotoPerfil(?string $foto_perfil): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFotoPerfil', [$foto_perfil]);

        parent::setFotoPerfil($foto_perfil);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', []);

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario(?\App\Entity\Usuario $id_usuario): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', [$id_usuario]);

        parent::setIdUsuario($id_usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeguidorPrincipal(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeguidorPrincipal', []);

        return parent::getSeguidorPrincipal();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeguidorPrincipal(\Doctrine\Common\Collections\Collection $seguidor_principal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeguidorPrincipal', [$seguidor_principal]);

        parent::setSeguidorPrincipal($seguidor_principal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeguidorFollower(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeguidorFollower', []);

        return parent::getSeguidorFollower();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeguidorFollower(\Doctrine\Common\Collections\Collection $seguidor_follower): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeguidorFollower', [$seguidor_follower]);

        parent::setSeguidorFollower($seguidor_follower);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicacion(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicacion', []);

        return parent::getPublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicacion(\Doctrine\Common\Collections\Collection $publicacion): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicacion', [$publicacion]);

        parent::setPublicacion($publicacion);
    }

}
