<?php

namespace ContainerMQjxIdO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NPtAZ4HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nPtAZ4H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nPtAZ4H'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'converters' => ['privates', 'App\\Controller\\DTO\\DTOConverters', 'getDTOConvertersService', true],
            'repository' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
            'utilidades' => ['privates', 'App\\Utilidades\\Utilidades', 'getUtilidadesService', true],
            'utils' => ['privates', 'App\\Utilidades\\Utilidades', 'getUtilidadesService', true],
        ], [
            'converters' => 'App\\Controller\\DTO\\DTOConverters',
            'repository' => 'App\\Repository\\UsuarioRepository',
            'utilidades' => 'App\\Utilidades\\Utilidades',
            'utils' => 'App\\Utilidades\\Utilidades',
        ]);
    }
}
