<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2vYYevx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2vYYevx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2vYYevx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2vYYevx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2vYYevx\App_KernelDevDebugContainer([
    'container.build_hash' => '2vYYevx',
    'container.build_id' => 'c2fb896e',
    'container.build_time' => 1675448536,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2vYYevx');
