<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMQjxIdO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMQjxIdO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMQjxIdO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMQjxIdO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMQjxIdO\App_KernelDevDebugContainer([
    'container.build_hash' => 'MQjxIdO',
    'container.build_id' => '57f1e51f',
    'container.build_time' => 1675798059,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMQjxIdO');
