<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDRPlsRo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDRPlsRo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDRPlsRo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDRPlsRo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDRPlsRo\App_KernelDevDebugContainer([
    'container.build_hash' => 'DRPlsRo',
    'container.build_id' => '161e7585',
    'container.build_time' => 1676045681,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDRPlsRo');
