<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], [], []],
    'app_access_token' => [[], ['_controller' => 'App\\Controller\\AccessTokenController::index'], [], [['text', '/access/token']], [], [], []],
    'app_comentario' => [[], ['_controller' => 'App\\Controller\\ComentarioController::index'], [], [['text', '/comentario']], [], [], []],
    'app_like' => [[], ['_controller' => 'App\\Controller\\LikeController::index'], [], [['text', '/like']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'app_mensaje' => [[], ['_controller' => 'App\\Controller\\MensajeController::index'], [], [['text', '/mensaje']], [], [], []],
    'app_perfil' => [[], ['_controller' => 'App\\Controller\\PerfilController::index'], [], [['text', '/perfil']], [], [], []],
    'app_perfil_listar' => [[], ['_controller' => 'App\\Controller\\PerfilController::listar'], [], [['text', '/perfil/listar']], [], [], []],
    'app_perfil_guardar' => [[], ['_controller' => 'App\\Controller\\PerfilController::save'], [], [['text', '/perfil/guardar']], [], [], []],
    'app_perfil_eliminar' => [['id'], ['_controller' => 'App\\Controller\\PerfilController::eliminar'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/perfil/eliminar']], [], [], []],
    'app_permiso' => [[], ['_controller' => 'App\\Controller\\PermisoController::index'], [], [['text', '/permiso']], [], [], []],
    'app_publicacion' => [[], ['_controller' => 'App\\Controller\\PublicacionController::index'], [], [['text', '/publicacion']], [], [], []],
    'app_publicacaion' => [[], ['_controller' => 'App\\Controller\\PublicacionController::listarPublicacion'], [], [['text', '/publicacion/listar']], [], [], []],
    'app_publicacaion_listar_usuario' => [['id'], ['_controller' => 'App\\Controller\\PublicacionController::listarPublicacionporPerfil'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/publicacion/listar']], [], [], []],
    'app_publicacaion_crear' => [[], ['_controller' => 'App\\Controller\\PublicacionController::guardarPublicacion'], [], [['text', '/publicacion/guardar']], [], [], []],
    'app_publicacaion_eliminar' => [['id'], ['_controller' => 'App\\Controller\\PublicacionController::eliminarPublicacion'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/publicacion/eliminar']], [], [], []],
    'app_publicacaion_editar' => [[], ['_controller' => 'App\\Controller\\PublicacionController::editarPublicacion'], [], [['text', '/publicacion/editar']], [], [], []],
    'app_rol' => [[], ['_controller' => 'App\\Controller\\RolController::index'], [], [['text', '/rol']], [], [], []],
    'app_rol_guardar' => [[], ['_controller' => 'App\\Controller\\RolController::saveRol'], [], [['text', '/rol/guardar']], [], [], []],
    'app_seguidor' => [['id'], ['_controller' => 'App\\Controller\\SeguidorController::listarseguidoresporidusuario'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/seguidores/listar']], [], [], []],
    'app_seguidores' => [['id'], ['_controller' => 'App\\Controller\\SeguidorController::listarseguidosporidusuario'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/seguidos/listar']], [], [], []],
    'app_eliminar_seguidor' => [['id', 'id_seguidor'], ['_controller' => 'App\\Controller\\SeguidorController::eliminarseguidor'], [], [['variable', '/', '[^/]++', 'id_seguidor', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/seguidor/eliminar']], [], [], []],
    'app_dejar_seguir' => [['id', 'id_seguido'], ['_controller' => 'App\\Controller\\SeguidorController::dejardeseguir'], [], [['variable', '/', '[^/]++', 'id_seguido', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/seguido/eliminar']], [], [], []],
    'app_usuario' => [[], ['_controller' => 'App\\Controller\\UsuarioController::index'], [], [['text', '/api/usuario']], [], [], []],
    'app_usuario_listar' => [[], ['_controller' => 'App\\Controller\\UsuarioController::listar'], [], [['text', '/api/usuario/listar']], [], [], []],
    'app_usuario_buscar' => [['id'], ['_controller' => 'App\\Controller\\UsuarioController::buscar'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/usuario/listar']], [], [], []],
    'app_usuario_crear' => [[], ['_controller' => 'App\\Controller\\UsuarioController::save'], [], [['text', '/usuario/guardar']], [], [], []],
];
